services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livemesh-web
    environment:
      NODE_ENV: "production"
      PORT: "3000"
    ports:
      - "3000:3000"     # <-- publish to host so Nginx/you can hit 127.0.0.1:3000
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - livemesh_net

networks:
  livemesh_net:
    driver: bridge
